default_config:
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.1.245:3218/
    require_admin: true
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant
    url: http://192.168.1.245:1880/
    require_admin: true
  frigate:
    title: Frigate
    url: http://192.168.1.245:5000/
    icon: mdi:cctv
    require_admin: true
  
recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 30

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids: 
      - !secret telegram_chat_id

notify:
  - platform: telegram
    name: !secret telegram_chat_name
    chat_id: !secret telegram_chat_id

automation: !include automations.yaml

sensor:
  - platform: aemet
    name: "AEMET"
    api_key: !secret aemet_api_key
    station_id: "1484C"
    monitored_conditions:
      - temperature
      - humidity
      - pressure
      - precipitation
      - snow
      - visibility
      - wind_speed
      - wind_max_speed
      - wind_bearing

shelly:
  discovery: true
  version: true
  sensors:
    - all

