default_config:
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.1.245:3218/
    require_admin: true
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant
    url: http://192.168.1.245:1880/
    require_admin: true
mqtt:
  broker: 192.168.1.245
  
recorder:
  db_url: mysql://homeassistant:eO97IIPl1a1e41m9@192.168.1.245/ha_db?charset=utf8
  purge_keep_days: 30
